name: feevo
description: "Feel the music. Live the vibe."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # State Management
  provider: ^6.1.2

  # Navigation
  go_router: ^14.2.7

  # Network
  dio: ^5.4.3

  # Backend
  supabase_flutter: ^2.5.0

  # Audio

  just_audio: ^0.9.36
  audio_service: ^0.18.12
  just_audio_background: ^0.0.1-beta.11

  # UI
  google_fonts: ^6.2.1
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0

  # Utils
  shared_preferences: ^2.2.3

  # Share
  share_plus: ^7.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/cats/
    - assets/images/
    - assets/images/flags/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 800
